### ISSUE TITLE
Solution of ticket #8 broke our project by not extending UINavigationBars to the top of the screen

### ISSUE THREAD

**Issue by cmittendorf** [rob-brown/RBStoryboardLink#14]
HI Rob,

today we updated our project to the latest version of RBStoryboardLink and we ran into a problem caused by what I think changed as a result of ticket #8. Our project uses SWRevealController together with RBStoryboardLink. It contains one storyboard containing the main navigation and a number of storyboards for the main user interaction. The content storyboards do contain a NSNavigationController as their initial view controller.

After this update the status bar no longer showed the tint color of the navigation controller, it was white instead (the color came from the content view of the RBStoryboardLink view controller).

Until now I came up with two "solutions":

The first solution would apply the tint color of the navigation bar to the white background view of a custom RBStoryboardLink subclass in viewDidLoad.

The other solution uses a subclass of RBStoryboardLink changing the viewDidLoad method to use the following layout constraint for the vertical positioning: @"V:|[view]|" instead of @"V:[topGuide][view][bottomGuide]". 

https://github.com/cmittendorf/RBStoryBoardLinkWithSWRevealControllerDemo

Do you have an idea for a better solution?

Regards
Christian

**Comment by ingltapia** [comment]
@CanTheAlmighty You just save my life. Worked fine for me. Thanks!
