### ISSUE TITLE
iOS 6?

### ISSUE THREAD

**Issue by RQEBMM** [rob-brown/RBStoryboardLink#17]
You mention in the readme it can be modified for iOS 6 pretty easily, but do not give any explanation of how/why. I was able to figure out a simplistic way of doing it (wrapping the iOS 7-only property pass-throughs and the  needsTop/BottomLayoutGuide stuff in checks of the OS version) but I'm not 100% it covers all the use cases.

**Comment by andres-ciano** [comment]
While I work around with all the comments here to support iOS6, it won't hurt to check. Did anybody work out a fork or patch or something for this?
In any case thanks @RQEBMM for the great explanation!
