### ISSUE TITLE
How to work with auto layout in linked storyboards?

### ISSUE THREAD

**Issue by buguibu** [rob-brown/RBStoryboardLink#32]
Maybe i'm wrong because i'm newbie in AutoLayout, but in the examples the linked storyboards don't use Auto Layout, do there is a way to work with them?

This is my configuration:

```
-SWRevealViewController
 |-> (SWRevealViewControllerSegue) -> sw_front
 |-> (SWRevealViewControllerSegue) -> sw_rear

-(sw_rear)UITableViewController
 |(each row selection)
 |-> SWRevealViewControllerSegue -> (CommonContainer)

-CommonContainer
 |-> Container -> Embed segue for container -> RBStoryboardLink

- RBStoryboardLink
 |->(User defined runtime attributes) "storyboardName" : "target_storyboard"

-SpecfificControllerOfTargetedStoryboard
 -(void)viewDidLoad{
    UIBarButtonItem * button = //...
    self.topViewController.navigationItem.rightBarButtonItem = button;//DOESN'T WORK
```

**Comment by Ashton-W** [comment]
I don't fully understand your problem @buguibu, **RBStoryboardLink** doesn't interfere with auto-layout as far as I know.
Could you upload a sample project?

**Comment by buguibu** [comment]
Sorry, i have lost access to the buggy project that i refer in the issue, so i'll had to build it again and there is no time for that, close the issue if you want.
