### ISSUE TITLE
Compatibility with Typhoon

### ISSUE THREAD

**Issue by fatuhoku** [rob-brown/RBStoryboardLink#33]
I'd be great if there's a documented example that shows how RBStoryboardLink works with [Typhoon](https://github.com/typhoon-framework/Typhoon): i.e. show that the `initialViewController` becomes the `destinationController`, whose properties have a chance of being injected with dependencies.

Has any one tried using this?

**Comment by rob-brown** [comment]
To keep `RBStoryboardLink` simple, I'll leave the Typhoon dependency in @papcio28's fork.
