### ISSUE TITLE
Unwind Segues are not passed to the child view controller

### ISSUE THREAD

**Issue by RVijay007** [rob-brown/RBStoryboardLink#5]
I'm having an issue where my unwind segues are not passed to the child view controller of the Storyboard Link. The canPerformUnwindSegue method correctly detects whether the child view controller implements the desired unwind method, but the method is called on the StoryboardLink instead of the child view controller. I ended up adding forwarding invocation code to your class to get the messages passed to the correct controller.

``` objective-c
- (BOOL)respondsToSelector:(SEL)aSelector {
    if ([super respondsToSelector:aSelector])
        return YES;
    else {
        return [self.scene respondsToSelector:aSelector];
    }
    return NO;
}

- (NSMethodSignature *)methodSignatureForSelector:(SEL)aSelector {
    NSMethodSignature* signature = [super methodSignatureForSelector:aSelector];
    if (!signature) {
        signature = [self.scene methodSignatureForSelector:aSelector];
    }
    return signature;
}

- (void)forwardInvocation:(NSInvocation *)anInvocation {
    if ([self.scene respondsToSelector:[anInvocation selector]])
        [anInvocation invokeWithTarget:self.scene];
    else
        [super forwardInvocation:anInvocation];
}
```

**Comment by nonstriater** [comment]
that's really a bad idea, -forwardInvocation cause so many bugs.detail see #68 #71
