### ISSUE TITLE
Problems with CocoaPods

### ISSUE THREAD

**Issue by PhilipSharman** [rob-brown/RBStoryboardLink#51]
When I try to build the project in XCode, I get the error message "error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation."

I just installed CocoaPods, so as far as I can tell it is up to date.

And when I run 'pod install', I get this error:
"Fetching podspec for `RBStoryboardLink` from `../RBStoryboardLink.podspec`
[!] Unable to satisfy the following requirements:
- `RBStoryboardLink (from `../RBStoryboardLink.podspec`)` required by `Podfile`
- `RBStoryboardLink (= 0.1.0)` required by `Podfile.lock`"

I'm new to CocoaPods, so I'm probably missing something obvious.  Any help would be appreciated, thanks.

**Comment by rob-brown** [comment]
I've made some updates to the pod. This shouldn't be an issue any more. If you continue to see this problem, then use `pod update` instead of `pod install`. `pod update` ignores the versions used by `Podfile.lock` and installs the newest version it can.
