### ISSUE TITLE
Layouts extending below bars are flawed (iOS 7)

### ISSUE THREAD

**Issue by Wirsing84** [rob-brown/RBStoryboardLink#8]
Hi Rob,
thank you for your efforts, I really fancy the idea.
However, I am experiencing problems with iOS 7.
I am using a TabBar-Controller Setup as in the respective Demo Project.
Scrollview / tableview content is not inset to account for the translucent menu bar, navigation bar and tab bar.
The Adjust Scroll View Insets Option is set to YES via IB in the Navigation Controller of the TabBar Storyboard as well as the Initial View Controller of the linked Storyboard.

I added
    self.automaticallyAdjustsScrollViewInsets = scene.automaticallyAdjustsScrollViewInsets;
    self.extendedLayoutIncludesOpaqueBars = scene.extendedLayoutIncludesOpaqueBars;
to RBStoryboardlink.m - to no effect.

Help is greatly appreciated!

Cheers
Chris

**Comment by fatuhoku** [comment]
Hmmm. I have navigation controllers in the same storyboard as the tab bar controller. I specifically set "Hide Bottom Bar on Push", but the bottom bar (tab bar) still shows after the push.

I don't quite understand how bottom layout guides are supposed to help with this.

@Wirsing84  @rob-brown Help!
